audit_header: false
title: Myrtle Beach's Best Real Estate Training
description: -- CLIENT NAME --, a top Real Estate Agent in -- MARKET --, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: /events/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Our Vision
    url: /vision/
  - title: Videos
    url: /videos
  - title: Business Plan
    url: /business-plan/

client:
  name: Greg Harrelson
  title:
  license_number:
  about_markdown: |
    Greg Harrelson has helped more people buy or sell in the Myrtle Beach market than any other agent in the past 15 years. To accomplish this, Greg Harrelson has dedicated himself to hard work and a relentless pursuit to being the most knowledgeable agent in the market and tops in the country.

    Greg is a former coach for The Mike Ferry Organization and has helped many agents reach top producer status selling 100, 200 and more homes per year.

    One of the Gregâ€™s greatest accomplishments is being #1 in the country for Highest Production Per Agent in the country. In order to achieve this, Greg had to commit his time and effort to developing real estate agents within his organization. He is known to be the go-to coach for high production results.

    He has created a productive environment that allows agents to grow their business fast and in a sustainable manner while maintaining a positive team-like culture within the organization.
  market: Myrtle Beach
  brand: The Harrelson Group
  brokerage: Century 21
  address: 4999 Carolina Forest Blvd, Ste. 18<br>Myrtle Beach, SC 29579
  phone: 843-903-3550
  phone_type: Office
  phone2: 843-457-7816
  phone2_type: Cell
  email: gregharrelson@gmail.com
  url: http://www.c21TheHarrelsonGroup.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MyrtleBeachsTopAgentMastermind/
  linkedin_url: https://www.linkedin.com/in/gregharrelson/
  gplus_url:
  youtube_url: https://www.youtube.com/user/MyrtleBeachProperty
  twitter_url: https://twitter.com/Gregharrelson
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.JPG
  hero_logo_path: /img/logo.png
  hero_logo_path2: /img/logo2.png
  hero_logo_path3: /img/logo3.png
  logo_width_number: 50
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#BDAE85'
  theme_color: '#404042'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#EFEAD7'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
